;SamplingPeriod	采样周期
;RangeL 量程下限
;RangeH 量程上限
;AlarmL 报警下限
;AlarmH 报警上限
;RangeUnit 	量程单位
;AlarmUnit 	报警单位
;SrcUnit 	仪器输出单位
;DispUnit=sccm	界面显示单位
;DestUnit=sccm	入库单位


;报警下限
;SO2	<=-14μg/m3
;NO	<=-6μg/m3
;NO2	<=-10μg/m3
;O3	<=-10μg/m3
;CO	<=-1mg/m3
;PM10	<=-5μg/m3
;PM2.5	<=-5μg/m3

[Cal]
SamplingPeriod=15
RangeL=0
RangeH=10000
AlarmL=0
AlarmH=10000
RangeUnit=sccm
AlarmUnit=sccm
SrcUnit=sccm
DispUnit=sccm
DestUnit=sccm

[BC]
SamplingPeriod=15
RangeL=0
RangeH=200
AlarmL=0
AlarmH=200
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[CH4]
SamplingPeriod=15
RangeL=0
RangeH=500
AlarmL=0
AlarmH=357.14
RangeUnit=ppm
AlarmUnit=mg/m3
SrcUnit=ppb
DispUnit=ppb
DestUnit=ppb

[NMHC]
SamplingPeriod=15
RangeL=0
RangeH=500
AlarmL=0
AlarmH=357.14
RangeUnit=ppm
AlarmUnit=mg/m3
SrcUnit=ppb
DispUnit=ppb
DestUnit=ppb

[CO]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=25
AlarmL=-1
AlarmH=1
AlarmH_Limit=true
RangeUnit=ppm
AlarmUnit=mg/m3
SrcUnit=ppb
DispUnit=mg/m3
DestUnit=mg/m3

[CO2]
SamplingPeriod=15
RangeL=0
RangeH=500
AlarmL=0
AlarmH=982.14
RangeUnit=ppm
AlarmUnit=ppm
SrcUnit=ppm
DispUnit=ppm
DestUnit=ppm

[DIF]
SamplingPeriod=15
RangeL=0
RangeH=500
AlarmL=0
AlarmH=1026.79
RangeUnit=ppb
AlarmUnit=μg/m3
SrcUnit=ppb
DispUnit=μg/m3
DestUnit=mg/m3

[NO]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=500
AlarmL=-6
AlarmH=1000
AlarmH_Limit=true
RangeUnit=ppb
AlarmUnit=μg/m3
SrcUnit=ppb
DispUnit=μg/m3
DestUnit=mg/m3

[NO.Y]
SamplingPeriod=15
RangeL=0
RangeH=500
AlarmL=0
AlarmH=669.64
RangeUnit=ppb
AlarmUnit=μg/m3
SrcUnit=ppb
DispUnit=μg/m3
DestUnit=mg/m3

[NO2]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=500
AlarmL=-10
AlarmH=1000
AlarmH_Limit=true
RangeUnit=ppb
AlarmUnit=μg/m3
SrcUnit=ppb
DispUnit=μg/m3
DestUnit=mg/m3

[NOx]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=500
AlarmL=0
AlarmH=1000
AlarmH_Limit=true
RangeUnit=ppb
AlarmUnit=μg/m3
SrcUnit=ppb
DispUnit=μg/m3
DestUnit=mg/m3

[NOy]
SamplingPeriod=15
RangeL=0
RangeH=500
AlarmL=0
AlarmH=1026.79
RangeUnit=ppb
AlarmUnit=μg/m3
SrcUnit=ppb
DispUnit=μg/m3
DestUnit=mg/m3

[O3]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=500
AlarmL=-10
AlarmH=1000
AlarmH_Limit=true
RangeUnit=ppb
AlarmUnit=μg/m3
SrcUnit=ppb
DispUnit=μg/m3
DestUnit=mg/m3

[SO2]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=500
AlarmL=-14
AlarmH=2000
AlarmH_Limit=true
RangeUnit=ppb
AlarmUnit=μg/m3
SrcUnit=ppb
DispUnit=μg/m3
DestUnit=mg/m3

[PM1]
SamplingPeriod=15
RangeL=0
RangeH=1000
AlarmL=0
AlarmH=1000
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM10]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=5000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM2.5]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-01]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-02]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-03]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-04]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-05]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-06]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3
[PM2.5-07]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-08]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-09]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-10]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-11]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-12]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-13]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-14]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-15]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-16]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-17]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-18]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-19]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-20]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-21]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-22]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=μg/m3

[PM2.5-23]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM2.5-24]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM2.5-25]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM2.5-26]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM2.5-27]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM2.5-28]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM2.5-29]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[PM2.5-30]
SamplingPeriod=15
AlarmL_Enabled=false
RangeL=0
RangeH=1000
AlarmL=-5
AlarmH=3000
AlarmH_Limit=true
RangeUnit=μg/m3
AlarmUnit=μg/m3
SrcUnit=μg/m3
DispUnit=μg/m3
DestUnit=mg/m3

[风速]
SamplingPeriod=5
RangeL=0
RangeH=50
AlarmL=0
AlarmH=50
RangeUnit=m/s
AlarmUnit=m/s
SrcUnit=m/s
DispUnit=m/s
DestUnit=m/s

[风向]
SamplingPeriod=5
RangeL=0
RangeH=360
AlarmL=0
AlarmH=360
RangeUnit=°
AlarmUnit=°
SrcUnit=°
DispUnit=°
DestUnit=°

[气温]
SamplingPeriod=10
RangeL=-50
RangeH=50
AlarmL=-50
AlarmH=50
RangeUnit=℃
AlarmUnit=℃
SrcUnit=℃
DispUnit=℃
DestUnit=℃

[气压]
SamplingPeriod=10
RangeL=900
RangeH=1100
AlarmL=900
AlarmH=1100
RangeUnit=hPa
AlarmUnit=hPa
SrcUnit=hPa
DispUnit=hPa
DestUnit=hPa

[湿度]
SamplingPeriod=10
RangeL=0
RangeH=100
AlarmL=0
AlarmH=100
RangeUnit=%
AlarmUnit=%
SrcUnit=%
DispUnit=%
DestUnit=%

[降水强度]
SamplingPeriod=60
RangeL=0
RangeH=100
AlarmL=0
AlarmH=100
RangeUnit=mm/h
AlarmUnit=mm/h
SrcUnit=mm/h
DispUnit=mm/h
DestUnit=mm/h

[能见度]
SamplingPeriod=60
RangeL=0
RangeH=100
AlarmL=0
AlarmH=100
RangeUnit=km
AlarmUnit=km
SrcUnit=km
DispUnit=km
DestUnit=km

[日照]
SamplingPeriod=60
RangeL=0
RangeH=2000
AlarmL=0
AlarmH=2000
RangeUnit=w/m2
AlarmUnit=w/m2
SrcUnit=w/m2
DispUnit=w/m2
DestUnit=w/m2

[EMS]
SamplingPeriod=5
RangeL=0
RangeH=100
AlarmL=0
AlarmH=100
RangeUnit=
AlarmUnit=
SrcUnit=
DispUnit=
DestUnit=

